//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaGae.Projects.RCC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaGae.Projects.RCC.Properties.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVR-Dude configuration not found in appsettings.json!.
        /// </summary>
        internal static string ErrorAVRDudeConfigNullAssignment {
            get {
                return ResourceManager.GetString("ErrorAVRDudeConfigNullAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification of data failed!.
        /// </summary>
        internal static string ErrorDataModificationFailed {
            get {
                return ResourceManager.GetString("ErrorDataModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for modification found!.
        /// </summary>
        internal static string ErrorEmptyDataArray {
            get {
                return ResourceManager.GetString("ErrorEmptyDataArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware configuration not found in appsettings.json!.
        /// </summary>
        internal static string ErrorFirmwareConfigNullAssignment {
            get {
                return ResourceManager.GetString("ErrorFirmwareConfigNullAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware download failed!.
        /// </summary>
        internal static string ErrorFirmwareDownloadFailed {
            get {
                return ResourceManager.GetString("ErrorFirmwareDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing HEX line failed!.
        /// </summary>
        internal static string ErrorInvalidHexLine {
            get {
                return ResourceManager.GetString("ErrorInvalidHexLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading serial ports failed!.
        /// </summary>
        internal static string ErrorLoadingSerialPorts {
            get {
                return ResourceManager.GetString("ErrorLoadingSerialPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a serial port!.
        /// </summary>
        internal static string ErrorNoCOMPortSelected {
            get {
                return ResourceManager.GetString("ErrorNoCOMPortSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is outside data area!.
        /// </summary>
        internal static string ErrorPositionOutsideDataarea {
            get {
                return ResourceManager.GetString("ErrorPositionOutsideDataarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer (AVR-Dude) download failed!.
        /// </summary>
        internal static string ErrorProgrammerDownloadFailed {
            get {
                return ResourceManager.GetString("ErrorProgrammerDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming of the device failed!.
        /// </summary>
        internal static string ErrorProgrammingFailed {
            get {
                return ResourceManager.GetString("ErrorProgrammingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting AVR-Dude failed!.
        /// </summary>
        internal static string ErrorStartingAVRDude {
            get {
                return ResourceManager.GetString("ErrorStartingAVRDude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Thread Exception.
        /// </summary>
        internal static string ErrorUnhandledThreadException {
            get {
                return ResourceManager.GetString("ErrorUnhandledThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled UI Exception.
        /// </summary>
        internal static string ErrorUnhandledUIException {
            get {
                return ResourceManager.GetString("ErrorUnhandledUIException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageBoxInformationTitle {
            get {
                return ResourceManager.GetString("MessageBoxInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading AVR-Dude!.
        /// </summary>
        internal static string MessageLoadingAVRDude {
            get {
                return ResourceManager.GetString("MessageLoadingAVRDude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading confguration!.
        /// </summary>
        internal static string MessageLoadingConfiguration {
            get {
                return ResourceManager.GetString("MessageLoadingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading firmware!.
        /// </summary>
        internal static string MessageLoadingFirmware {
            get {
                return ResourceManager.GetString("MessageLoadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting application!.
        /// </summary>
        internal static string MessageStartingApplication {
            get {
                return ResourceManager.GetString("MessageStartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming completed successfully!.
        /// </summary>
        internal static string StatusProgrammingCompleted {
            get {
                return ResourceManager.GetString("StatusProgrammingCompleted", resourceCulture);
            }
        }
    }
}
